apiVersion: fedramp20x-poc/v1
kind: CryptographicModule
metadata:
  name: openssl-fips-provider
  uuid: 95beec7e-6f82-4aaa-8211-969cd7c1f1ab
  labels:
    data-classification:
      - DIT
      - DAR
    environment: production
    component: api-gateway
  annotations:
    ssp-reference: "SC-13"
    last-assessment: "2025-01-15"

spec:
  module:
    name: "OpenSSL FIPS Provider"
    vendor:
      name: "OpenSSL Software Foundation"
      url: "https://www.openssl.org"
    type: software
    embodiment: multi-chip-standalone
    versions:
      software: "3.0.8"
    description: "FIPS 140-3 validated cryptographic provider for OpenSSL 3.x"

  validation:
    standard: "FIPS 140-3"
    certificateNumber: 4282
    securityLevel: 1
    validationDate: "2023-10-03"
    sunsetDate: "2028-10-03"
    cmvpUrl: "https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4282"
    algorithms:
      - AES
      - RSA
      - ECDSA
      - SHA-2
      - SHA-3
      - HMAC
      - KDF
      - DRBG
    caveats:
      - "No assurance of minimum strength of generated SSPs"

  usage:
    dataClassification:
      - data-in-transit
    location: "Application Server - TLS Termination"
    purpose: "TLS 1.3 encryption for API endpoints"
    inherited: false

  portProtocolServiceRef:
    - "pps-001"
    - "pps-002"

status:
  cmvpStatus: Active
  lastValidated: "2025-12-07T10:30:00Z"
  complianceStatus: compliant
